### ISSUE TITLE
Upload and download functionality breaks after trying to download a jpg

### ISSUE THREAD

**Issue by ReneSmeekes** [storj-thirdparty/vortex#96]
When you download a jpg file it opens in the browser window instead of downloading. If you hit the back button to return to the file browser  file uploads and downloads no longer work. A page refresh doesn't seem to fix the issue, but navigating to another tab and back does.

Tested in brave browser.

**Comment by super3** [comment]
@ReneSmeekes Was not able to re-create on Brave. Can you try logging out and logging in again, and see if that fixes the issue. Might be a caching thing.

**Comment by ReneSmeekes** [comment]
My bad, I did some further testing. It works as expected for files uploaded using the browser. The issue seems to only occur with files uploaded using the S3 settings.

The same problem seems to happen when downloading png or txt files uploaded over the S3 compatibility. Likely with any filetype that can be opened natively by the browser. It also happens in Chrome and Edge, just verified that.

To replicate:
1. Upload a jpg, png or txt file using the S3 settings on the second tab
2. Open the file browser in one of the mentioned browsers
3. Attempt to download the file uploaded in step 1 (it will open in the browser window)
4. Use the back button in the browser to get back to the file browser
5. Download and upload functionality are now broken until you navigate to a different tab and back

I uploaded the exact same file (just renamed) through the browser interface and it downloaded as expected, so this seems to be limited to files uploaded through other clients.

**Comment by super3** [comment]
@gabedealmeida @montyanderson I think we have to force a download by saying its an attachment in the headers somehow: 
https://stackoverflow.com/questions/36936605/node-express-force-browser-to-download-file-with-custom-name

**Comment by gabedealmeida** [comment]
@super3 I think adding the download attribute might do the trick. It's working on my end.

**Comment by super3** [comment]
@ReneSmeekes I believe we fixed this issue. Can you confirm?

**Comment by ReneSmeekes** [comment]
@super3 is this change actually live already? I'm still seeing the same behavior. Though I think the proposed solution is the correct way to go about it.

Though I believe if you set the download attribute to value 'download' it will result in the downloaded file being named 'download'. In html you can just include it without a value to use the original filename. Like `<a href="https://something" download>link</a>`, but it doesn't look like the value is optional in the setAttribute method. Maybe if you pass it null?

**Comment by gabedealmeida** [comment]
@ReneSmeekes Thanks for the response! I've gone ahead and set the value to the file name. @super3 I've committed the changes to the `force-download` branch.

**Comment by super3** [comment]
@ReneSmeekes Ok those changes have been deployed. Can you try it again now?

**Comment by ReneSmeekes** [comment]
Unfortunately I'm still seeing the same behavior. All file types that are supported by the browser still open in the browser instead of downloading (when uploaded through s3).

**Comment by montyanderson** [comment]
Traditionally this is done with http response headers, which we can't control because it comes from MT.
